parameters:

services:
  # Конфигурация по умолчанию (только для этого файла)
  _defaults:
    # Включает механизм автоматической подстановки зависимостей контейнера в ваши сервисы
    autowire: true
    # Включает механизм автоконфигурации
    autoconfigure: true

  Jasmcoder\TicketingCommonBundle\Service\Validator\:
    resource: '../src/Service/Validator/*'
